export type ThemeColors = {
    primary: string;
    planMode: string;
    selection: string;
    thinking: string;
    success: string;
    error: string;
    info: string;
    background: string;
    surface: string;
    dialogSurface: string;
    thinkingBorder: string;
    dimSeparator: string;
    text: string;
    textMuted: string;
    textOnSelection: string;
};

export type Theme = {
    name: string;
    colors: ThemeColors;
};

export const THEMES: Theme[] = [
    {
        name: "Nkhalango",
        colors: {
            primary: "#56D6C2",
            planMode: "#CF8EF4",
            selection: "#89B4FA",
            thinking: "#CF8EFE",
            success: "#82E0AA",
            error: "#E74C5E",
            info: "#56D6C2",
            background: "#0D0D12",
            surface: "#1A1A24",
            dialogSurface: "#0A0A10",
            thinkingBorder: "#34344A",
            dimSeparator: "#4E4E66",
            text: "#E1E1E1",
            textMuted: "#6B7280",
            textOnSelection: "#000000",
        },
    },
    {
        name: "Moto",
        colors: {
            primary: "#BD93F9",
            planMode: "#FF79C6",
            selection: "#6272A4",
            thinking: "#FF79C6",
            success: "#50FA7B",
            error: "#FF5555",
            info: "#8BE9FD",
            background: "#282A36",
            surface: "#44475A",
            dialogSurface: "#21222C",
            thinkingBorder: "#6272A4",
            dimSeparator: "#6272A4",
            text: "#F8F8F2",
            textMuted: "#6272A4",
            textOnSelection: "#FFFFFF",
        },
    },
    {
        name: "Bunda",
        colors: {
            primary: "#FBBF24",
            planMode: "#F97316",
            selection: "#D97706",
            thinking: "#F97316",
            success: "#86EFAC",
            error: "#F87171",
            info: "#FBBF24",
            background: "#1C1410",
            surface: "#261C14",
            dialogSurface: "#110C08",
            thinkingBorder: "#44300A",
            dimSeparator: "#6B4A14",
            text: "#D6D3D1",
            textMuted: "#78716C",
            textOnSelection: "#FFFFFF",
        },
    },
    {
        name: "Kuwala",
        colors: {
            primary: "#FF2D95",
            planMode: "#00E5FF",
            selection: "#00E5FF",
            thinking: "#FF2D95",
            success: "#39FF14",
            error: "#FF0055",
            info: "#00E5FF",
            background: "#1A0A2E",
            surface: "#2D1B4E",
            dialogSurface: "#10051E",
            thinkingBorder: "#4A2D7A",
            dimSeparator: "#6B4D9E",
            text: "#F0E6FF",
            textMuted: "#9B7EC8",
            textOnSelection: "#000000",
        },
    },
    {
        name: "Mphamvu",
        colors: {
            primary: "#339E66",
            planMode: "#CE1126",
            selection: "#FFD700",
            thinking: "#CE1126",
            success: "#339E66",
            error: "#CE1126",
            info: "#339E66",
            background: "#0A0A0A",
            surface: "#1A1A1A",
            dialogSurface: "#050505",
            thinkingBorder: "#CE1126",
            dimSeparator: "#333333",
            text: "#F0F0F0",
            textMuted: "#888888",
            textOnSelection: "#000000",
        },
    },
    {
        name: "Blantyre",
        colors: {
            primary: "#FB923C",
            planMode: "#FBBF24",
            selection: "#EA580C",
            thinking: "#FBBF24",
            success: "#4ADE80",
            error: "#F43F5E",
            info: "#FB923C",
            background: "#160C04",
            surface: "#221508",
            dialogSurface: "#0D0602",
            thinkingBorder: "#4A2008",
            dimSeparator: "#703010",
            text: "#D6D3D1",
            textMuted: "#78716C",
            textOnSelection: "#FFFFFF",
        },
    },
    {
        name: "Zotuwa",
        colors: {
            primary: "#E0E0E0",
            planMode: "#BBBBBB",
            selection: "#555555",
            thinking: "#BBBBBB",
            success: "#CCCCCC",
            error: "#999999",
            info: "#AAAAAA",
            background: "#0F0F0F",
            surface: "#1F1F1F",
            dialogSurface: "#080808",
            thinkingBorder: "#3A3A3A",
            dimSeparator: "#555555",
            text: "#F0F0F0",
            textMuted: "#777777",
            textOnSelection: "#FFFFFF",
        },
    },
    {
        name: "Kasinja",
        colors: {
            primary: "#2563EB",
            planMode: "#7C3AED",
            selection: "#BFDBFE",
            thinking: "#7C3AED",
            success: "#059669",
            error: "#DC2626",
            info: "#0284C7",
            background: "#F8FAFC",
            surface: "#E2E8F0",
            dialogSurface: "#F1F5F9",
            thinkingBorder: "#CBD5E1",
            dimSeparator: "#94A3B8",
            text: "#0F172A",
            textMuted: "#64748B",
            textOnSelection: "#1E293B",
        },
    },
    {
        name: "Pepala",
        colors: {
            primary: "#8B5CF6",
            planMode: "#A78BFA",
            selection: "#FDE68A",
            thinking: "#A78BFA",
            success: "#059669",
            error: "#DC2626",
            info: "#0284C7",
            background: "#FFF8F0",
            surface: "#F5EDE0",
            dialogSurface: "#FAF4EA",
            thinkingBorder: "#E8DDD0",
            dimSeparator: "#A89888",
            text: "#3D2E1E",
            textMuted: "#8B7D6B",
            textOnSelection: "#1C140E",
        },
    },
    {
        name: "Lilongwe",
        colors: {
            primary: "#FF6B9D",
            planMode: "#C084FC",
            selection: "#F472B6",
            thinking: "#C084FC",
            success: "#A3E635",
            error: "#FB7185",
            info: "#F472B6",
            background: "#1E1420",
            surface: "#2A1D30",
            dialogSurface: "#120C16",
            thinkingBorder: "#3F284A",
            dimSeparator: "#5C3F6A",
            text: "#F3E8FF",
            textMuted: "#8A6E9E",
            textOnSelection: "#FFFFFF",
        },
    },
    {
        name: "Zomba",
        colors: {
            primary: "#81A1C1",
            planMode: "#A3BE8C",
            selection: "#5E81AC",
            thinking: "#8FBCBB",
            success: "#A3BE8C",
            error: "#BF616A",
            info: "#88C0D0",
            background: "#1E2530",
            surface: "#2B3340",
            dialogSurface: "#141A22",
            thinkingBorder: "#3B4252",
            dimSeparator: "#4C566A",
            text: "#ECEFF4",
            textMuted: "#6B7A8E",
            textOnSelection: "#FFFFFF",
        },
    },
    {
        name: "Tchowa",
        colors: {
            primary: "#FF7F50",
            planMode: "#DDA0DD",
            selection: "#FF6347",
            thinking: "#DDA0DD",
            success: "#7DCEA0",
            error: "#E74C3C",
            info: "#FF7F50",
            background: "#0E0A1A",
            surface: "#1A142E",
            dialogSurface: "#080510",
            thinkingBorder: "#2A2242",
            dimSeparator: "#433860",
            text: "#E8E0F0",
            textMuted: "#7A6E96",
            textOnSelection: "#FFFFFF",
        },
    },
    {
        name: "Mulanje",
        colors: {
            primary: "#6B8E23",
            planMode: "#DAA520",
            selection: "#8FBC8F",
            thinking: "#556B2F",
            success: "#6B8E23",
            error: "#CD5C5C",
            info: "#8FBC8F",
            background: "#141D14",
            surface: "#1D2A1D",
            dialogSurface: "#0C120C",
            thinkingBorder: "#2D402D",
            dimSeparator: "#436043",
            text: "#E0E8D8",
            textMuted: "#708A70",
            textOnSelection: "#FFFFFF",
        },
    },
    {
        name: "Shire",
        colors: {
            primary: "#4682B4",
            planMode: "#6A5ACD",
            selection: "#5B9BD5",
            thinking: "#6A5ACD",
            success: "#3CB371",
            error: "#CD5C5C",
            info: "#4682B4",
            background: "#0C141E",
            surface: "#141E2C",
            dialogSurface: "#080E14",
            thinkingBorder: "#1E3040",
            dimSeparator: "#334C60",
            text: "#D0DCE8",
            textMuted: "#687C90",
            textOnSelection: "#FFFFFF",
        },
    },
    {
        name: "Nyanja",
        colors: {
            primary: "#5F9EA0",
            planMode: "#B0C4DE",
            selection: "#7EC8E3",
            thinking: "#B0C4DE",
            success: "#8FBC8F",
            error: "#CD853F",
            info: "#5F9EA0",
            background: "#1E2628",
            surface: "#283234",
            dialogSurface: "#141A1C",
            thinkingBorder: "#3A4648",
            dimSeparator: "#506064",
            text: "#DCE8E8",
            textMuted: "#70868A",
            textOnSelection: "#FFFFFF",
        },
    },
    {
        name: "Nyasa",
        colors: {
            primary: "#20B2AA",
            planMode: "#87CEEB",
            selection: "#00CED1",
            thinking: "#87CEEB",
            success: "#48C774",
            error: "#FF6B6B",
            info: "#64D8D0",
            background: "#00202E",
            surface: "#002A3D",
            dialogSurface: "#001018",
            thinkingBorder: "#0E4C6A",
            dimSeparator: "#1A6A8A",
            text: "#C8E8F0",
            textMuted: "#5090A8",
            textOnSelection: "#FFFFFF",
        },
    },
    {
        name: "Thyolo",
        colors: {
            primary: "#8B7355",
            planMode: "#C4A882",
            selection: "#A0522D",
            thinking: "#C4A882",
            success: "#7D9B76",
            error: "#C0392B",
            info: "#8B7355",
            background: "#F5F0EA",
            surface: "#EBE3D8",
            dialogSurface: "#FAF6F0",
            thinkingBorder: "#D4CAB8",
            dimSeparator: "#A89888",
            text: "#2C2218",
            textMuted: "#8B7D6B",
            textOnSelection: "#1C140E",
        },
    },
    {
        name: "Chilengedwe",
        colors: {
            primary: "#7A9A7A",
            planMode: "#B8C4A8",
            selection: "#8FB08F",
            thinking: "#B8C4A8",
            success: "#6B8E6B",
            error: "#C0685C",
            info: "#8AAE8A",
            background: "#F0F5EE",
            surface: "#E4EBE0",
            dialogSurface: "#F5F8F2",
            thinkingBorder: "#CDD8C8",
            dimSeparator: "#9AA8A0",
            text: "#1A241A",
            textMuted: "#7A8A78",
            textOnSelection: "#1C241C",
        },
    },
    {
        name: "Mdima",
        colors: {
            primary: "#60A5FA",
            planMode: "#A78BFA",
            selection: "#3B82F6",
            thinking: "#818CF8",
            success: "#34D399",
            error: "#F87171",
            info: "#60A5FA",
            background: "#000000",
            surface: "#0F0F0F",
            dialogSurface: "#000000",
            thinkingBorder: "#1F1F1F",
            dimSeparator: "#333333",
            text: "#F5F5F5",
            textMuted: "#666666",
            textOnSelection: "#000000",
        },
    },
    {
        name: "Kale",
        colors: {
            primary: "#FFB000",
            planMode: "#FF8C00",
            selection: "#FFD700",
            thinking: "#FF8C00",
            success: "#00FF00",
            error: "#FF4500",
            info: "#FFB000",
            background: "#000000",
            surface: "#0D0800",
            dialogSurface: "#000000",
            thinkingBorder: "#1A1500",
            dimSeparator: "#4A3A00",
            text: "#FFD866",
            textMuted: "#6B5A20",
            textOnSelection: "#000000",
        },
    },
];

export const DEFAULT_THEME = THEMES.find((t) => t.name === "Nkhalango")!;
